In [20]:
import pandas as pd
import numpy as np

In [2]:
data = [10,20,30]
se_d = pd.Series(data)
se_d

0    10
1    20
2    30
dtype: int64

In [3]:
#1. Write a Pandas program to change the order of index of a given series.
se_d = pd.Series(data,index=['A','B','c'])
se_d

A    10
B    20
c    30
dtype: int64

In [7]:
s1 = [2, 4, 6, 8, 10]
s2= [1, 3, 5, 7, 9]
s3 = pd.Series(s1)
s4 = pd.Series(s1)
print(s3)
print(s4)

0     2
1     4
2     6
3     8
4    10
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64


In [10]:
# 2. Write a Python program to add, subtract, multiple and divide two Pandas Series.
print(s3+s4)
print(s3-s4)
print(s3*s4)
print(s3/s4)

0     4
1     8
2    12
3    16
4    20
dtype: int64
0    0
1    0
2    0
3    0
4    0
dtype: int64
0      4
1     16
2     36
3     64
4    100
dtype: int64
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64


In [15]:
#3. Write a Python program to convert a Panda module Series to Python list and it's type
se_d.tolist # one way
se_d = list(se_d)
print(type(se_d))

<class 'list'>


In [35]:
# 4. Write a Pandas program to select the rows where the score is missing, i.e.is NaN 
exam_data = {'name': ['Sachin', 'Ganguly', 'Kohli', 'Johnson', 'Taylor',   
    'Waugh', 'Yuvraj', 'Kambli', 'Srinath', 'Munaf'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] 
df = pd.DataFrame(exam_data,index=labels)


In [36]:
print(df[df['score'].isnull()])

      name  score  attempts qualify
d  Johnson    NaN         3      no
h   Kambli    NaN         1      no


In [38]:
#5. Write a Pandas program to create todays date
import pandas as pd
from datetime import date
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print(now)

2019-12-07 00:00:00


In [39]:
#6 Write a Pandas program to create a Pivot table, by considering Titanic Dataset
ar =  np.arange(2, 11).reshape(3,3)
print(ar)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [41]:
# 7.Illustrate the difference between ravel and flatten by taking considering multidimensional array.
a = np.array( [ (1,7,3,4),(3,2,4,1) ] )
print(a.flatten())
print(a.ravel())

[1 7 3 4 3 2 4 1]
[1 7 3 4 3 2 4 1]


In [46]:
#10. Illustrate the concept of splitting by taking random positive values and also implementing different stacking methods on them.
ar =np.arange(1, 10).reshape(3,3)
print(ar)
print(np.hstack(ar))
print(np.vstack(ar))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])